# 使用 node:16.20.2-buster 基础镜像
FROM node:16.20.2-buster

# 设置环境变量以避免交互式安装
ENV DEBIAN_FRONTEND=noninteractive

# 安装 ADB 以及其他必要的包
RUN apt update && \
    apt install -y --no-install-recommends android-tools-adb git && \
    npm install -g node-gyp && \
    # 清理 apt 缓存以减少镜像大小
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /ws-scrcpy

# 克隆仓库
RUN git clone https://github.com/NetrisTV/ws-scrcpy.git .

# 安装依赖
RUN npm install

# 构建项目，并在构建过程中输出详细信息
# RUN npm run build || { echo 'Build failed'; exit 1; }
RUN npm run dist

# 确认文件已存在
RUN ls -al /ws-scrcpy/dist || { echo 'dist directory not found'; exit 1; }

# 暴露端口
EXPOSE 8000

# 默认命令
CMD ["node", "dist/index.js"]
