# 使用 node:16.20.2-buster 基础镜像
FROM node:16.20.2-buster

# 安装 ADB 以及其他必要的包
RUN apt update && \
    apt install android-tools-adb -y && \
    npm install -g node-gyp

# 设置工作目录
WORKDIR /ws-scrcpy

RUN git clone https://github.com/NetrisTV/ws-scrcpy.git

# 暴露端口
EXPOSE 8000

# 默认命令
# CMD ["node", "dist/index.js"]
CMD ["ping", "127.0.0.1"]
