name: Docker Image CI ws-scrcpy ws-scrcpy-alpine

on:
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  workflow_dispatch:  

env:
  DOCKER_HUB_REPOSITORY: testaction
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # 最大运行60分钟
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Set Timezone and Get Date
      run: |
        sudo apt-get install -y tzdata
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "Asia/Shanghai" | sudo tee /etc/timezone
        DATE_TAG=$(date +'%Y%m%d%H%M%S')
        echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile-ws-alpine
        platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:ws-scrcpy-alpine-${{ env.DATE_TAG }}
